# Serverless deployment config
service: fplabs

# AWS env variables
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-2

# Function scaffolding
functions:
  probe:
    handler: handler.test
    events:
      - http:
          path: test
          method: post
